server:
  port: 8800

spring:
  data:
    mongodb:
      database: demo
      username: root
      password: root
      host: localhost
      port: 27017
      authentication-database: admin

mongock:
  migration-scan-package: com.petrovic.demo.migration
