FROM gradle:7.5.1-jdk17-alpine as build-stage
WORKDIR /app
COPY build.gradle .
COPY src src
RUN gradle clean build -x test

FROM amazoncorretto:17-alpine-jdk as prod-stage
LABEL maintainer = "DevTech"
COPY --from=build-stage /app/build/libs/*.jar demo.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar", "demo.jar"]