FROM maven:3.8.6-amazoncorretto-17 as build-stage
WORKDIR /app
COPY pom.xml .
COPY src src
RUN mvn package -DskipTests --no-transfer-progress

FROM amazoncorretto:17-alpine-jdk as prod-stage
LABEL maintainer = "DevTech"
COPY --from=build-stage /app/target/demo.jar demo.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar", "demo.jar"]