version: "3.8"

services:

  mongodb:
    image: mongo:latest
    restart: on-failure

    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_DATABASE=demo

  demoApp:
    image: demo
    build:
      context: ../
      dockerfile: .Docker/dockerfile
    depends_on:
      - mongodb
    ports:
      - "8800:8800"